version: "3.9"
services:
  blossom-dashboard:
    container_name: blossom-dashboard
    image: blossom-dashboard:latest
    # build if image does not exist
    build: .
    volumes:
      # Note that CONFIG_DIR must be set to the ABSOLUTE PATH of your secrets directory. All config files must point to a base dir of /config
      - $CONFIG_DIR:/config
    command: /config/config.yaml
    ports:
      - 80:80
