# Sample Config File (edit to fit your needs)
connectionProfilePath: ~/profile.yaml
channel: test
contract: blossom
endorsingOrganizations:
  - m-...
identities:
  - name: client1
    mspid: m-...
    certPath: ~/
    privateKeyPath: ~/
    listenToEvents: true
